### ISSUE TITLE
"Internal error executing the custom function" error

### ISSUE THREAD

**Issue by tmockler69** [nuadi/googlecrestscript#11] opened 2016-02-02 02:10 UTC
i'm receiving the error for all cells containing the GetItemPriceList function.  Has something changed in Google Sheets?  I was not getting this error prior to today.

The GetItemPrice function is working fine....only the GetItemPriceList seems to be broken.

Thank you.

**Comment by nuadi** [comment] 2016-03-24 17:29
How many items are you using in the getItemPriceList function? Try cutting the size of the list in half, and see if it responds. Repeat that process until you get a response.

**Comment by nuadi** [comment] 2016-04-24 18:51
Did you have any luck with my suggestion?

**Comment by nuadi** [comment] 2016-05-14 14:14
Closing this just because I cannot reproduce the error without feedback. If you are still having this problem, open a new issue so we can try to sort this out.

**Comment by SubliminallyFamous** [comment] 2017-07-18 16:47
Hi, I've been having this issue too. At first I cut the call into half, then half again, but now I have it so it only calls 50 prices at a time and whilst it was working OK to begin with it's started to happen again. Any suggestions? Thanks. (Using the getmarketpricelist function)

**Comment by nuadi** [comment] 2017-07-18 17:06
Thank you for trying that out. Can you send me the list of items you are using? That way I can reproduce the issue on my end.

**Comment by SubliminallyFamous** [comment] 2017-07-18 17:14
Hi nuadi, I just got back to my computer and can see the function has refreshed and is working in some areas but not others. Another error being thrown now is: https://pastebin.com/hxFqgfnb
The items at that particular time was a complete list of drones with the function split every 50 lines. https://pastebin.com/gtGfBac8
Thanks

**Comment by nuadi** [comment] 2017-07-18 17:38
Okay, I'm getting the same error now when I use this list. The function is taking approximately 35-40 seconds to kick back an #ERROR! response, which means it's most likely hitting the 30 second time limit on custom functions. However! Google doesn't tell us that's the case, so I will put in code to test for that.

That other error is easy to fix. I'll look into the function to make sure it pauses between CREST calls. I hate to add my own sleep timer since we only get 30 seconds per function call already. I don't want to eat into that, but maybe I can reverse engineer Google's rate limit.

**Comment by SubliminallyFamous** [comment] 2017-07-18 17:39
Awesome, thanks! I'll keep an eye out here should you need any more data etc.

**Comment by nuadi** [comment] 2017-08-20 13:59
I took a look at this function, and decided it was time to sunset the entire `getMarketItemList` function. As such, moving forward it will be removed from GCS until CCP gives us a proper endpoint for list-based calls.

You are welcome to keep the function code in future scripts. Just copy it from a previous version and it should continue to work for the time being, but I will no longer maintain nor support it.

**Closed as completed by nuadi** 2017-08-20 13:59 UTC
Labels: bug
